version: '3.8'
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - "8080:8080"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
##  - /var/lib/docker/:/var/lib/docker:ro if you're using linux
    - /dev/disk/:/dev/disk:ro
    depends_on:
    - redis
    devices:
    - /dev/kmsg:/dev/kmsg
  redis:
    image: redis:latest
    container_name: redis
    ports:
    - "6379:6379"
